---
name: Release artifacts

on:
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  release:
    name: Release artifacts
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      -
        name: Determine build version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      -
        name: Display build version information
        run: |
          echo "Commit Date: ${{ steps.gitversion.outputs.commitDate }}"
          echo "Branch Name: ${{ steps.gitversion.outputs.branchName }}"
          echo "Commit Sha: ${{ steps.gitversion.outputs.sha }}"
          echo "(Current) Pre-Release SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "Release SemVer: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo ""
          echo "This repo follows the Conventional Commits specification to trigger vesion bumps."
          echo "https://www.conventionalcommits.org/en/v1.0.0/"
          echo ""
          echo "You can also manually specify the version by pushing a git tag of the form vX.X"
          echo "or vX.X.X"
      -
        name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ steps.gitversion.outputs.majorMinorPatch }}
          release_name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}