---
name: Unit Tests

on:
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Run tests
        run: go test github.com/kekkerz/gosm/...